model_parameters:
  T: 1.0           # Maturity (in years)
  n_steps: 250     # Numbers of timestep
  H: 0.07          # Hurst Exponant
  eta: 1.9         # Vol of vol
  rho: -0.9        # Correlation between price and vol
  xi: 0.04         # Forward variance
  S0: 100.0        # Initial spot price


simulation_settings:
  n_paths: 5000    # Numbers of path of Monte Carlo Sim
  seed: 42         
