model_parameters:
  T: 1.0           # Maturity (in years)
  n_steps: 500     # Numbers of timestep
  H: 0.07        # Hurst Exponant
  eta: 1.9         # Vol of vol
  rho: -0.2    # Correlation between price and vol
  xi: 0.055225         # Forward variance
  S0: 100.0        # Initial spot price
  r: 0.0 # Risk free rate 


simulation_settings:
  n_paths: 5_000    # Numbers of path of Monte Carlo Sim
  seed: 2001         
