model_parameters:
  T: 1.0           # Maturity (in years)
  n_steps: 500     # Numbers of timestep
  H: 0.5         # Hurst Exponant
  eta: 1.9         # Vol of vol
  rho: 0        # Correlation between price and vol
  xi: 0.04         # Forward variance
  S0: 100.0        # Initial spot price


simulation_settings:
  n_paths: 50000    # Numbers of path of Monte Carlo Sim
  seed: 42         
